[package]
name = "sv_parse"
version = "0.1.0"
edition = "2021"

[lib]
name = "sv_parse"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.2", features = ["extension-module"] }
thiserror = "2.0.3"
